### ISSUE TITLE
How to configure servers?

### ISSUE THREAD

**Issue by cjbottaro** [tsharju/memcache_client#4]
How do you configure what memcached servers to connect to?  Can add to readme?

**Comment by fishtreesugar** [comment]
@cjbottaro

example config:

``` elixir
config :memcache_client,
  host: "127.0.0.1",
  port: 11211,
  auth_method: :none,
  username: "",
  password: "",
  pool_size: 10,
  pool_max_overflow: 20
```

**Comment by cjbottaro** [comment]
Ahh, thank you.

What about if you have multiple memcached clusters?

**Comment by fishtreesugar** [comment]
I think this client haven't handle this situation.

Sent using CloudMagic [https://cloudmagic.com/k/d/mailapp?ct=pi&cv=6.1.51&pv=8.2]
On Mon, Jun 13, 2016 at 23:55, Christopher J. Bottaro notifications@github.com wrote:
Ahh, thank you.

What about if you have multiple memcached clusters?
